# 3 Control Flow in R

<div id="buttons">
<a class="btn btn-primary btn-lg" role="button" href="lectures/03_week.html">Lecture Slides (html)</a>
<a class="btn btn-info btn-lg" role="button" href="https://github.com/ASDS-TCD/POP77001_Computer_Programming_2022/blob/main/lectures/03_week.pdf">Lecture Slides (pdf)</a>
<a class="btn btn-secondary btn-lg" role="button" href="https://github.com/ASDS-TCD/POP77001_Computer_Programming_2022/blob/main/lectures/03_week.ipynb">Lecture Slides (ipynb)</a>
<br>
<br>
<a class="btn btn-success btn-lg" role="button" href="https://github.com/ASDS-TCD/POP77001_Computer_Programming_2022/blob/main/tutorials/03_week.ipynb">Tutorial Exercise (ipynb)</a>
<a class="btn btn-info btn-lg" role="button" href="https://github.com/ASDS-TCD/POP77001_Computer_Programming_2022/blob/main/tutorials/03_week.pdf">Tutorial Exercise (pdf)</a>
<a class="btn btn-secondary btn-lg" role="button" href="tutorials/03_week.html">Tutorial Exercise (html)</a>
<br>
<br>
<a class="btn btn-danger btn-lg" role="button" href="https://github.com/ASDS-TCD/POP77001_Computer_Programming_2022/blob/main/assignments/01_assignment.ipynb">Assignment</a>
</div>
---

This week we will focus on the key ways of controlling the flow of programs in R. We will look at branching and loops, common for all programming languages and the details of their design in R.

## Required Readings

- Peng Ch 14: Control Structures;
- Wickham Ch [5: Control Flow](https://adv-r.hadley.nz/control-flow.html);

## Additional Readings

- Matloff Ch 7: R Programming Structures.

## Tutorial

- Conditional statements and iterations;
- Working with functions in R.

## Assignment 1

- R Basics and control flow.
- Due at 23:59 on Friday, 30th September (submission on Blackboard);
- Rename the file from `01_assignment.ipynb` to `01_assignment_lastname_firstname_studentnumber.ipynb` before submission.
